/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.saluddigital.cerroverde.view;

import java.awt.event.ItemEvent;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.DefaultComboBoxModel;

import com.saluddigital.cerroverde.controller.PacienteController;
import com.saluddigital.cerroverde.model.Paciente;

/**
 *
 * @author Piero Giovanni
 */
public class RegistroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form PanelPaciente
     */
    public RegistroPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        cboTipoDoc = new javax.swing.JComboBox<>();
        txtDocumento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboTipoEC = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cboTipoSexo = new javax.swing.JComboBox<>();
        cboTipoGrSa = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSeguroSocial = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCorreoE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cboDepartamento = new javax.swing.JComboBox<>();
        cboProvincia = new javax.swing.JComboBox<>();
        cboDistrito = new javax.swing.JComboBox<>();
        btnCrearPaciente = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Paciente");

        jLabel8.setText("Documento");

        cboTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Tipo-", "DNI", "C.E.", "Pasaporte", "Otros" }));

        jLabel2.setText("Primer Apellido");

        jLabel3.setText("Segundo Apellido");

        jLabel4.setText("Primer Nombre");

        jLabel5.setText("Segundo nombre");

        jLabel6.setText("Estado Civil");

        cboTipoEC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Viudo", "DIvorciado" }));

        jLabel1.setText("Sexo");

        cboTipoSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        cboTipoGrSa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        jLabel18.setText("Grupo Sanguineo");

        jLabel9.setText("Seguro Social");

        jLabel10.setText("Nacionalidad");

        jLabel7.setText("Nacimiento");

        jLabel13.setText("Edad");

        txtEdad.setEditable(false);

        jLabel11.setText("Telefono");

        jLabel12.setText("Correo Electronico");

        jLabel14.setText("Direccion");

        jLabel15.setText("Departamento");

        jLabel16.setText("Provincia");

        jLabel17.setText("Distrito");

        cboDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Amazonas", "Ancash", "Apurimac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huanuco", "Ica", "Junin", "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martin", "Tacna", "Tumbes", "Ucayali" }));
        cboDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDepartamentoItemStateChanged(evt);
            }
        });

        cboProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-" }));
        cboProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProvinciaItemStateChanged(evt);
            }
        });

        cboDistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-" }));

        btnCrearPaciente.setText("Crear Paciente");
        btnCrearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPacienteActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrearPaciente)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(cboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(cboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(cboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(txtPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(txtSNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cboTipoEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(cboTipoGrSa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cboTipoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtSeguroSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(cboTipoEC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSeguroSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboTipoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboTipoGrSa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearPaciente)
                    .addComponent(btnLimpiar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDepartamentoItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            // Obtiene el departamento seleccionado
            String departamentoSeleccionado = (String) cboDepartamento.getSelectedItem();
            
            // Mapas de cada departamento con sus provincias correspondientes
            Map<String, List<String>> provinciasPorDepartamento = new HashMap<>();
            provinciasPorDepartamento.put("-Seleccione-", Arrays.asList("-Seleccione-"));
            provinciasPorDepartamento.put("Amazonas", Arrays.asList("-Seleccione-", "Bagua", "Bongara", "Chachapoyas", "Condorcanqui", "Luya", "Rodriguez de Mendoza", "Utcubamba"));
            provinciasPorDepartamento.put("Ancash", Arrays.asList("-Seleccione-", "Aija", "Antonio Raymondi", "Asuncion", "Bolognesi", "Carhuaz", "Carlos Fermin Fitzcarrald", "Casma", "Corongo", "Huaraz", "Huari", "Huarmey", "Huaylas", "Mariscal Luzuriaga", "Ocros", "Pallasca", "Pomabamba", "Recuay", "Santa", "Sihuas", "Yungay"));
            provinciasPorDepartamento.put("Apurimac", Arrays.asList("-Seleccione-", "Abancay", "Andahuaylas", "Antabamba", "Aymaraes", "Chincheros", "Cotabambas", "Grau"));
            provinciasPorDepartamento.put("Arequipa", Arrays.asList("-Seleccione-", "Arequipa", "Camana", "Caraveli", "Castilla", "Caylloma", "Condesuyos", "Islay", "La Union"));
            provinciasPorDepartamento.put("Ayacucho", Arrays.asList("-Seleccione-", "Cangallo", "Huamanga", "Huanca Sancos", "Huanta", "La Mar", "Lucanas", "Parinacochas", "Paucar del Sara Sara", "Sucre", "Victor Fajardo", "Vilcas Huaman"));
            provinciasPorDepartamento.put("Cajamarca", Arrays.asList("-Seleccione-", "Cajabamba", "Cajamarca", "Celendin", "Chota", "Contumaza", "Cutervo", "Hualgayoc", "Jaen", "San Ignacio", "San Marcos", "San Miguel", "San Pablo", "Santa Cruz"));
            provinciasPorDepartamento.put("Callao", Arrays.asList("-Seleccione-", "Callao"));
            provinciasPorDepartamento.put("Cusco", Arrays.asList("-Seleccione-", "Acomayo", "Anta", "Calca", "Canas", "Canchis", "Chumbivilcas", "Cusco", "Espinar", "La Convencion", "Paruro", "Paucartambo", "Quispicanchi", "Urubamba"));
            provinciasPorDepartamento.put("Huancavelica", Arrays.asList("-Seleccione-", "Acobamba", "Angaraes", "Castrovirreyna", "Churcampa", "Huancavelica", "Huaytara", "Tayacaja"));
            provinciasPorDepartamento.put("Huanuco", Arrays.asList("-Seleccione-", "Ambo", "Dos de Mayo", "Huacaybamba", "Huanuco", "Lauricocha", "Leoncio Prado", "Mara�on", "Pachitea", "Puerto Inca", "Luya", "Rodriguez de Mendoza", "Huanuco", "Huamalies"));
            provinciasPorDepartamento.put("Ica", Arrays.asList("-Seleccione-", "Chincha", "Ica", "Nazca", "Palpa", "Pisco"));
            provinciasPorDepartamento.put("Junin", Arrays.asList("-Seleccione-", "Chanchamayo", "Chupaca", "Concepcion", "Huancayo", "Jauja", "Junin", "Satipo", "Tarma", "Yauli"));
            provinciasPorDepartamento.put("La Libertad", Arrays.asList("-Seleccione-", "Ascope", "Bolivar", "Chepen", "Gran Chim�", "Julcan", "Otuzco", "Pacasmayo", "Pataz", "Sanchez Carrion", "Santiago de Chuco", "Trujillo", "Viru"));
            provinciasPorDepartamento.put("Lambayeque", Arrays.asList("-Seleccione-", "Chiclayo", "Ferrenafe", "Lambayeque"));
            provinciasPorDepartamento.put("Lima", Arrays.asList("-Seleccione-", "Barranca", "Cajatambo", "Canta", "Ca�ete", "Huaral", "Huarochiri", "Huaura", "Lima", "Oyon", "Yauyos"));
            provinciasPorDepartamento.put("Loreto", Arrays.asList("-Seleccione-", "Alto Amazonas", "Loreto", "Mariscal Ramon Castilla", "Maynas", "Requena", "Ucayali"));
            provinciasPorDepartamento.put("Madre de Dios", Arrays.asList("-Seleccione-", "Manu", "Tahuamanu", "Tambopata"));
            provinciasPorDepartamento.put("Moquegua", Arrays.asList("-Seleccione-", "General Sanchez Cerro", "Ilo", "Mariscal Nieto"));
            provinciasPorDepartamento.put("Pasco", Arrays.asList("-Seleccione-", "Daniel Alcides Carrion", "Oxapampa", "Pasco"));
            provinciasPorDepartamento.put("Piura", Arrays.asList("-Seleccione-", "Ayabaca", "Huancabamba", "Morropon", "Paita", "Piura", "Sechura", "Sullana", "Talara"));
            provinciasPorDepartamento.put("Puno", Arrays.asList("-Seleccione-", "Azangaro", "Carabaya", "Chucuito", "El Collao", "Huancane", "Lampa", "Melgar", "Moho", "Puno", "San Antonio de Putina", "San Roman", "Sandia", "Yunguyo"));
            provinciasPorDepartamento.put("San Martin", Arrays.asList("-Seleccione-", "Bellavista", "El Dorado", "Huallaga", "Lamas", "Mariscal Caceres", "Moyobamba", "Picota", "Rioja", "San Martin", "Tocache"));
            provinciasPorDepartamento.put("Tacna", Arrays.asList("-Seleccione-", "Candarave", "Jorge Basadre", "Tacna", "Tarata"));
            provinciasPorDepartamento.put("Tumbes", Arrays.asList("-Seleccione-", "Contralmirante Villar", "Tumbes", "Zarumilla"));
            provinciasPorDepartamento.put("Ucayali", Arrays.asList("-Seleccione-", "Atalaya", "Coronel Portillo", "Padre Abad"));
            
            List<String> provincias = provinciasPorDepartamento.get(departamentoSeleccionado);
            cboProvincia.removeAllItems();
            
            for (String provincia : provincias) {
                cboProvincia.addItem(provincia);
            }
        }
    }//GEN-LAST:event_cboDepartamentoItemStateChanged

    private void cboProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProvinciaItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            String provinciaSeleccionada = (String) cboProvincia.getSelectedItem();
            Map<String, List<String>> distritosPorProvincia = new HashMap<>();        
            
            distritosPorProvincia.put("-Seleccione-", Arrays.asList("-Seleccione-"));
            // Amazonas
            distritosPorProvincia.put("Bagua", Arrays.asList("-Seleccione-", "Aramango", "Bagua", "Copallin", "El Parco", "Imaza", "La Peca"));
            distritosPorProvincia.put("Bongara", Arrays.asList("-Seleccione-", "Chisquilla", "Churuja", "Corosha", "Cuispes", "Florida", "Jazan", "Jumbilla", "Recta", "San Carlos", "Shipasbamba", "Valera", "Yambrasbamba"));
            distritosPorProvincia.put("Chachapoyas", Arrays.asList("-Seleccione-", "Asuncion", "Balsas", "Chachapoyas", "Cheto", "Chiliquin", "Chuquibamba", "Granada", "Huancas", "La Jalca", "Leimebamba", "Levanto", "Magdalena", "Mariscal Castilla", "Molinopampa", "Montevideo", "Olleros", "Quinjalca", "San Francisco de Daguas", "San Isidro de Maino", "Soloco", "Sonche"));
            distritosPorProvincia.put("Condorcanqui", Arrays.asList("-Seleccione-", "El Cenepa", "Nieva", "R�o Santiago"));
            distritosPorProvincia.put("Luya", Arrays.asList("-Seleccione-", "Camporredondo", "Cocabamba", "Colcamar", "Conila", "Inguilpata", "Lamud", "Longuita", "Lonya Chico", "Luya", "Luya Viejo", "Mar�a", "Ocalli", "Ocumal", "Pisuquia", "Providencia", "San Cristobal", "San Francisco del Yeso", "San Jer�nimo", "San Juan de Lopecancha", "Santa Catalina", "Santo Tomas", "Tingo", "Trita"));
            distritosPorProvincia.put("Rodriguez de Mendoza", Arrays.asList("-Seleccione-", "Chirimoto", "Cochamal", "Huambo", "Limabamba", "Longar", "Mariscal Benavides", "Milpuc", "Omia", "Santa Rosa", "Totora", "Vista Alegre"));
            distritosPorProvincia.put("Utcubamba", Arrays.asList("-Seleccione-", "Bagua Grande", "Cajaruro", "Cumba", "El Milagro", "Jamalca", "Lonya Grande", "Yamon", "Yambrasbamba"));
            // Ancash
            distritosPorProvincia.put("Aija", Arrays.asList("-Seleccione-", "Aija", "Coris", "Huacllan", "La Merced", "Succha"));
            distritosPorProvincia.put("Antonio Raymondi", Arrays.asList("-Seleccione-", "Llamellin", "Aczo", "Chaccho", "Chingas", "Mirgas", "San Juan de Rontoy"));
            distritosPorProvincia.put("Asuncion", Arrays.asList("-Seleccione-", "Chacas", "Acochaca"));
            distritosPorProvincia.put("Bolognesi", Arrays.asList("-Seleccione-", "Chiquian", "Abelardo Pardo Lezameta", "Antonio Raymondi", "Aquia", "Cajacay", "Canis", "Colquioc", "Huallanca", "Huasta", "Huayllacayan", "La Primavera", "Mangas", "Pacllon", "San Miguel de Corpanqui", "Ticllos"));
            distritosPorProvincia.put("Carhuaz", Arrays.asList("-Seleccione-", "Carhuaz", "Acopampa", "Amashca", "Anta", "Ataquero", "Marcara", "Pariahuanca", "San Miguel de Aco", "Shilla", "Tinco", "Yungar"));
            distritosPorProvincia.put("Carlos Fermin Fitzcarrald", Arrays.asList("-Seleccione-", "San Luis", "San Nicol�s", "Yauya"));
            distritosPorProvincia.put("Casma", Arrays.asList("-Seleccione-", "Casma", "Buena Vista Alta", "Comandante Noel", "Yautan"));
            distritosPorProvincia.put("Corongo", Arrays.asList("-Seleccione-", "Corongo", "Aco", "Bambas", "Cusca", "La Pampa", "Yanac", "Yupan"));
            distritosPorProvincia.put("Huaraz", Arrays.asList("-Seleccione-", "Huaraz", "Cochabamba", "Colcabamba", "Huanchay", "Independencia", "Jangas", "La Libertad", "Olleros", "Pampas Grande", "Pariacoto", "Pira", "Tarica"));
            distritosPorProvincia.put("Huari", Arrays.asList("-Seleccione-", "Huari", "Anra", "Cajay", "Chavin de Huantar", "Huacachi", "Huacchis", "Huachis", "Huantar", "Masin", "Paucas", "Ponto", "Rahuapampa", "Rapayan", "San Marcos", "San Pedro de Chana", "Uco"));
            distritosPorProvincia.put("Huarmey", Arrays.asList("-Seleccione-", "Huarmey", "Cochapeti", "Culebras", "Huayan", "Malvas"));
            distritosPorProvincia.put("Huaylas", Arrays.asList("-Seleccione-", "Caraz", "Huallanca", "Huata", "Huaylas", "Mato", "Pamparomas", "Pueblo Libre", "Santa Cruz", "Santo Toribio", "Yuracmarca"));
            distritosPorProvincia.put("Mariscal Luzuriaga", Arrays.asList("-Seleccione-", "Piscobamba", "Casca", "Eleazar Guzm�n Barron", "Fidel Olivas Escudero", "Llama", "Llumpa", "Lucma", "Musga"));
            distritosPorProvincia.put("Ocros", Arrays.asList("-Seleccione-", "Ocros", "Acas", "Cajamarquilla", "Carhuapampa", "Cochas", "Congas", "Llipa", "San Cristobal de Rajan", "San Pedro", "Santiago de Chilcas"));
            distritosPorProvincia.put("Pallasca", Arrays.asList("-Seleccione-", "Cabana", "Bolognesi", "Conchucos", "Huacaschuque", "Huandoval", "Lacabamba", "Llapo", "Pallasca", "Pampas", "Santa Rosa", "Tauca"));
            distritosPorProvincia.put("Pomabamba", Arrays.asList("-Seleccione-", "Pomabamba", "Huayllan", "Parobamba", "Quinuabamba"));
            distritosPorProvincia.put("Recuay", Arrays.asList("-Seleccione-", "Recuay", "Catac", "Cotaparaco", "Huayllapampa", "Llacllin", "Marca", "Pararin", "Tapacocha", "Ticapampa", "Tocllaraju"));
            distritosPorProvincia.put("Santa", Arrays.asList("-Seleccione-", "Chimbote", "C�ceres del Per�", "Coishco", "Macate", "Moro", "Nepe�a", "Samanco", "Santa", "Nuevo Chimbote"));
            distritosPorProvincia.put("Sihuas", Arrays.asList("-Seleccione-", "Sihuas", "Acobamba", "Alfonso Ugarte", "Cashapampa", "Chingalpo", "Huayllabamba", "Quiches", "Ragash", "San Juan", "Sicsibamba", "Yungay"));
            distritosPorProvincia.put("Yungay", Arrays.asList("-Seleccione-", "Yungay", "Cascapara", "Mancos", "Matacoto", "Quillo", "Ranrahirca", "Shupluy", "Yanama"));
            // Apurimac
            distritosPorProvincia.put("Abancay", Arrays.asList("-Seleccione-", "Abancay", "Chacoche", "Circa", "Curahuasi", "Huanipaca", "Lambrama", "Pichirhua", "San Pedro de Cachora", "Tamburco"));
            distritosPorProvincia.put("Andahuaylas", Arrays.asList("-Seleccione-", "Andahuaylas", "Andarapa", "Chiara", "Huancarama", "Huancaray", "Huayana", "Kishuara", "Pacobamba", "Pacucha", "Pampachiri", "Pomacocha", "San Antonio de Cachi", "San Jer�nimo", "San Miguel de Chaccrampa", "Santa Mar�a de Chicmo", "Talavera", "Tumay Huaraca"));
            distritosPorProvincia.put("Antabamba", Arrays.asList("-Seleccione-", "Antabamba", "El Oro", "Huaquirca", "Juan Espinoza Medrano", "Oropesa", "Pachaconas", "Sabaino"));
            distritosPorProvincia.put("Aymaraes", Arrays.asList("-Seleccione-", "Chalhuanca", "Capaya", "Caraybamba", "Chapimarca", "Colcabamba", "Cotaruse", "Ihuayllo", "Justo Apu Sahuaraura", "Lucre", "Pocohuanca", "San Juan de Chac�a", "Sa�ayca", "Soraya", "Tapairihua", "Tintay"));
            distritosPorProvincia.put("Chincheros", Arrays.asList("-Seleccione-", "Chincheros", "Anco_Huallo", "Cocharcas", "Huaccana", "Ocobamba", "Ongoy", "Uranmarca", "Ranracancha", "Rocchacc", "El Porvenir", "Los Chankas", "R�o Grande"));
            distritosPorProvincia.put("Cotabambas", Arrays.asList("-Seleccione-", "Tambobamba", "Cotabambas", "Coyllurqui", "Haquira", "Mara", "Challhuahuacho"));
            distritosPorProvincia.put("Grau", Arrays.asList("-Seleccione-", "Chuquibambilla", "Curpahuasi", "Gamarra", "Huayllati", "Mamara", "Micaela Bastidas", "Pataypampa", "Progreso", "San Antonio", "Santa Rosa", "Turpay", "Vilcabamba", "Virundo", "Curasco"));
            // Arequipa
            distritosPorProvincia.put("Arequipa", Arrays.asList("-Seleccione-", "Arequipa", "Alto Selva Alegre", "Cayma", "Cerro Colorado", "Characato", "Chiguata", "Jacobo Hunter", "La Joya", "Mariano Melgar", "Miraflores", "Mollebaya", "Paucarpata", "Pocsi", "Polobaya", "Queque�a", "Sabandia", "Sachaca", "San Juan de Siguas", "San Juan de Tarucani", "Santa Isabel de Siguas", "Santa Rita de Siguas", "Socabaya", "Tiabaya", "Uchumayo", "Vitor", "Yanahuara", "Yarabamba", "Yura", "Jos� Luis Bustamante y Rivero"));
            distritosPorProvincia.put("Camana", Arrays.asList("-Seleccione-", "Camana", "Jose Maria Quimper", "Mariano Nicolas Valcarcel", "Mariscal Caceres", "Nicol�s de Pi�rola", "Oco�a", "Quilca", "Samuel Pastor"));
            distritosPorProvincia.put("Caraveli", Arrays.asList("-Seleccione-", "Caraveli", "Acari", "Atico", "Atiquipa", "Bella Union", "Cahuacho", "Chala", "Chaparra", "Huanuhuanu", "Jaqui", "Lomas", "Quicacha", "Yauca"));
            distritosPorProvincia.put("Castilla", Arrays.asList("-Seleccione-", "Aplao", "Andagua", "Ayo", "Chachas", "Chilcaymarca", "Choco", "Huancarqui", "Machaguay", "Orcopampa", "Pampacolca", "Tipan", "U�on", "Uraca", "Viraco"));
            distritosPorProvincia.put("Caylloma", Arrays.asList("-Seleccione-", "Chivay", "Achoma", "Cabanaconde", "Callalli", "Caylloma", "Coporaque", "Huambo", "Huanca", "Ichupampa", "Lari", "Lluta", "Maca", "Madrigal", "San Antonio de Chuca", "Sibayo", "Tapay", "Tisco", "Tuti", "Yanque"));
            distritosPorProvincia.put("Condesuyos", Arrays.asList("-Seleccione-", "Chuquibamba", "Andaray", "Cayarani", "Chichas", "Iray", "R�o Grande", "Salamanca", "Yanaquihua"));
            distritosPorProvincia.put("Islay", Arrays.asList("-Seleccione-", "Mollendo", "Cocachacra", "Dean Valdivia", "Islay", "Mejia", "Punta de Bombon"));
            distritosPorProvincia.put("La Union", Arrays.asList("-Seleccione-", "Cotahuasi", "Alca", "Charcana", "Huaynacotas", "Pampamarca", "Puyca", "Quechualla", "Sayla", "Tauria", "Tomepampa", "Toro"));
            // Ayacucho
            distritosPorProvincia.put("Cangallo", Arrays.asList("-Seleccione-", "Cangallo", "Chuschi", "Los Morochucos", "Maria Parado de Bellido", "Paras", "Totos"));
            distritosPorProvincia.put("Huamanga", Arrays.asList("-Seleccione-", "Acocro", "Acos Vinchos", "Andres Avelino Caceres Dorregaray", "Ayacucho", "Carmen Alto", "Chiara", "Jes�s Nazareno", "Ocros", "Pacaycasa", "Quinua", "San Jose de Ticllas", "San Juan Bautista", "Santiago de Pischa", "Socos", "Tambillo", "Vinchos"));
            distritosPorProvincia.put("Huanca Sancos", Arrays.asList("-Seleccione-", "Carapo", "Sacsamarca", "Sancos", "Santiago de Lucanamarca"));
            distritosPorProvincia.put("Huanta", Arrays.asList("-Seleccione-", "Ayahuanco", "Huamanguilla", "Huanta", "Iguain", "Llochegua", "Luricocha", "Santillana", "Sivia"));
            distritosPorProvincia.put("La Mar", Arrays.asList("-Seleccione-", "Anchihuay", "Ayna", "Chilcas", "Chungui", "Luis Carranza", "Oronccoy", "Pampamarca", "San Miguel", "Santa Rosa", "Tambo"));
            distritosPorProvincia.put("Lucanas", Arrays.asList("-Seleccione-", "Aucara", "Cabana", "Carmen Salcedo", "Chavi�a", "Chipao", "Huac-Huas", "Laramate", "Leoncio Prado", "Llauta", "Lucanas", "Oca�a", "Otoca", "Saisa", "San Cristobal", "San Juan", "San Pedro", "San Pedro de Palco", "Santa Ana de Huaycahuacho", "Santa Lucia"));
            distritosPorProvincia.put("Parinacochas", Arrays.asList("-Seleccione-", "Coracora", "Chumpi", "Coronel Castaneda", "Pacapausa", "Pullo", "Puyusca", "San Francisco de Ravacayco", "Upahuacho"));
            distritosPorProvincia.put("Paucar del Sara Sara", Arrays.asList("-Seleccione-", "Colta", "Corculla", "Lampa", "Marcabamba", "Oyolo", "Pararca", "Pausa", "San Javier de Alpabamba", "San Jose de Ushua", "Sara Sara"));
            distritosPorProvincia.put("Sucre", Arrays.asList("-Seleccione-", "Belen", "Chalcos", "Chilcayoc", "Huacana", "Morcolla", "Paico", "Querobamba", "San Pedro de Larcay", "San Salvador de Quije", "Santiago de Paucaray", "Soras"));
            distritosPorProvincia.put("Victor Fajardo", Arrays.asList("-Seleccione-", "Allauca", "Andarapa", "Chapimarca", "Huancapi", "Huancaraylla", "Huaya", "Sarhua", "Vilcanchos"));
            distritosPorProvincia.put("Vilcas Huaman", Arrays.asList("-Seleccione-", "Accomarca", "Carhuanca", "Concepcion", "Huambalpa", "Independencia", "Saurama", "Vischongo"));
            // Cajamarca            
            distritosPorProvincia.put("Cajabamba", Arrays.asList("-Seleccione-", "Cajabamba", "Cachachi", "Condebamba", "Sitacocha"));
            distritosPorProvincia.put("Cajamarca", Arrays.asList("-Seleccione-", "Asuncion", "Cajamarca", "Chetilla", "Cospan", "Encanada", "Jesus", "Llacanora", "Los Banos del Inca", "Magdalena", "Matara", "Namora", "San Juan"));
            distritosPorProvincia.put("Celendin", Arrays.asList("-Seleccione-", "Celendin", "Chumuch", "Cortegana", "Huasmin", "Jorge Chavez", "Jose Galvez", "La Libertad de Pallan", "Miguel Iglesias", "Oxamarca", "Sorochuco", "Sucre", "Utco", "La Encanada"));
            distritosPorProvincia.put("Chota", Arrays.asList("-Seleccione-", "Chota", "Anguia", "Chadin", "Chiguirip", "Chimban", "Choropampa", "Cochabamba", "Conchan", "Huambos", "Lajas", "Llama", "Miracosta", "Paccha", "Pion", "Querocoto", "San Juan de Licupis", "Tacabamba", "Tocmoche", "Chalamarca"));
            distritosPorProvincia.put("Contumaza", Arrays.asList("-Seleccione-", "Contumaza", "Chilete", "Cupisnique", "Guzmango", "San Benito", "Santa Cruz de Toledo", "Tantarica", "Yonan"));
            distritosPorProvincia.put("Cutervo", Arrays.asList("-Seleccione-", "Cutervo", "Callayuc", "Choros", "Cujillo", "La Ramada", "Pimpingos", "Querocotillo", "San Andres de Cutervo", "San Juan de Cutervo", "San Luis de Lucma", "Santa Cruz", "Santo Domingo de la Capilla", "Santo Tomas", "Socota", "Toribio Casanova"));
            distritosPorProvincia.put("Hualgayoc", Arrays.asList("-Seleccione-", "Bambamarca", "Chugur", "Hualgayoc"));
            distritosPorProvincia.put("Jaen", Arrays.asList("-Seleccione-", "Jaen", "Bellavista", "Chontali", "Colasay", "Huabal", "Las Pirias", "Pomahuaca", "Pucara", "Sallique", "San Felipe", "San Jose del Alto", "Santa Rosa"));
            distritosPorProvincia.put("San Ignacio", Arrays.asList("-Seleccione-", "San Ignacio", "Chirinos", "Huarango", "La Coipa", "Namballe", "San Jose de Lourdes", "Tabaconas"));
            distritosPorProvincia.put("San Marcos", Arrays.asList("-Seleccione-", "Pedro Galvez", "Chancay", "Eduardo Villanueva", "Gregorio Pita", "Ichocan", "Jose Manuel Quiroz", "Jose Sabogal", "La Florida", "Nanchoc", "Paccha", "San Antonio", "Santa Cruz", "Tongod", "Union Agua Blanca"));
            distritosPorProvincia.put("San Miguel", Arrays.asList("-Seleccione-", "San Miguel", "Bolivar", "Calquis", "Catilluc", "El Prado", "La Florida", "Llapa", "Nanchoc", "Niepos", "San Gregorio", "San Silvestre de Cochan", "Tongod", "Union Agua Blanca"));
            distritosPorProvincia.put("San Pablo", Arrays.asList("-Seleccione-", "San Pablo", "San Bernardino", "San Luis", "Tumbaden"));
            distritosPorProvincia.put("Santa Cruz", Arrays.asList("-Seleccione-", "Santa Cruz", "Andabamba", "Catache", "Chancaybanos", "La Esperanza", "Ninabamba", "Pulan", "Saucepampa", "Sexi", "Uticyacu", "Yauyucan"));
            // Cusco
            distritosPorProvincia.put("Acomayo", Arrays.asList("-Seleccione-", "Acomayo", "Acopia", "Acos", "Mosoc Llacta", "Pomacanchi", "Rondocan", "Sangarara"));
            distritosPorProvincia.put("Anta", Arrays.asList("-Seleccione-", "Anta", "Ancahuasi", "Cachimayo", "Chinchaypujio", "Huarocondo", "Limatambo", "Mollepata", "Pucyura", "Zurite"));
            distritosPorProvincia.put("Calca", Arrays.asList("-Seleccione-", "Calca", "Coya", "Lamay", "Lares", "Pisac", "San Salvador", "Taray", "Yanatile"));
            distritosPorProvincia.put("Canas", Arrays.asList("-Seleccione-", "Yanaoca", "Checca", "Kunturkanki", "Langui", "Layo", "Pampamarca", "Quehue", "Tupac Amaru", "Yaurisque"));
            distritosPorProvincia.put("Canchis", Arrays.asList("-Seleccione-", "Sicuani", "Checacupe", "Combapata", "Marangani", "Pitumarca", "San Pablo", "San Pedro", "Tinta"));
            distritosPorProvincia.put("Chumbivilcas", Arrays.asList("-Seleccione-", "Santo Tomas", "Capacmarca", "Chamaca", "Colquemarca", "Livitaca", "Llusco", "Qui�ota", "Velille"));
            distritosPorProvincia.put("Cusco", Arrays.asList("-Seleccione-", "Cusco", "Ccorca", "Poroy", "San Jeronimo", "San Sebastian", "Santiago", "Saylla", "Wanchaq"));
            distritosPorProvincia.put("Espinar", Arrays.asList("-Seleccione-", "Yauri", "Condoroma", "Coporaque", "Ocoruro", "Pallpata", "Pichigua", "Suyckutambo"));
            distritosPorProvincia.put("La Convencion", Arrays.asList("-Seleccione-", "Santa Ana", "Echarati", "Huayopata", "Maranura", "Ocobamba", "Quellouno", "Kimbiri", "Santa Teresa", "Vilcabamba", "Pichari"));
            distritosPorProvincia.put("Paruro", Arrays.asList("-Seleccione-", "Paruro", "Accha", "Ccapi", "Colcha", "Huanoquite", "Omacha", "Paccaritambo", "Pillpinto", "Yaurisque"));
            distritosPorProvincia.put("Paucartambo", Arrays.asList("-Seleccione-", "Paucartambo", "Caicay", "Challabamba", "Colquepata", "Huancarani", "Kosnipata", "Paucartambo"));
            distritosPorProvincia.put("Quispicanchi", Arrays.asList("-Seleccione-", "Urcos", "Andahuaylillas", "Camanti", "Ccarhuayo", "Ccatca", "Cusipata", "Huaro", "Lucre", "Marcapata", "Ocongate", "Oropesa", "Quiquijana"));
            distritosPorProvincia.put("Urubamba", Arrays.asList("-Seleccione-", "Urubamba", "Chinchero", "Huayllabamba", "Machupicchu", "Maras", "Ollantaytambo", "Yucay"));
            // Huancavelica
            distritosPorProvincia.put("Acobamba", Arrays.asList("-Seleccione-", "Acobamba", "Andabamba", "Anta", "Caja", "Marcas"));
            distritosPorProvincia.put("Angaraes", Arrays.asList("-Seleccione-", "Lircay", "Anchonga", "Callanmarca", "Ccochaccasa", "Chincho", "Congalla", "Huanca-Huanca", "Huayllay Grande", "Julcamarca", "San Antonio de Antaparco", "Santo Tomas de Pata", "Secclla"));
            distritosPorProvincia.put("Castrovirreyna", Arrays.asList("-Seleccione-", "Castrovirreyna", "Arma", "Aurahua", "Capillas", "Chupamarca", "Cocas", "Huachos", "Huamatambo", "Mollepampa", "San Juan", "Santa Ana", "Tantara"));
            distritosPorProvincia.put("Churcampa", Arrays.asList("-Seleccione-", "Churcampa", "Anco", "Chinchihuasi", "El Carmen", "La Merced", "Locroja", "Paucarbamba", "San Miguel de Mayocc", "San Pedro de Coris", "Pachamarca"));
            distritosPorProvincia.put("Huancavelica", Arrays.asList("-Seleccione-", "Huancavelica", "Acobambilla", "Acoria", "Conayca", "Cuenca", "Huachocolpa", "Huayllahuara", "Izcuchaca", "Laria", "Manta", "Mariscal Caceres", "Moya", "Nuevo Occoro", "Palca", "Pilchaca", "Vilca"));
            distritosPorProvincia.put("Huaytara", Arrays.asList("-Seleccione-", "Huaytara", "Ayavi", "Cordova", "Huayacundo Arma", "Laramarca", "Ocoyo", "Pilpichaca", "Querco", "Quito-Arma", "San Antonio de Cusicancha", "San Francisco de Sangayaico", "San Isidro", "Santiago de Chocorvos", "Santiago de Quirahuara", "Santo Domingo de Capillas", "Tambo", "Vinchos"));
            distritosPorProvincia.put("Tayacaja", Arrays.asList("-Seleccione-", "Pampas", "Acostambo", "Ahuaycha", "Colcabamba", "Daniel Hernandez", "Huachocolpa", "Huahua", "Laramarca", "Marcas", "Paucara", "Pazos", "Quichuas", "Quishuar", "San Antonio de Cusicancha", "San Francisco de Sangayaico", "San Isidro", "Santiago de Chocorvos"));
            // Huanuco
            distritosPorProvincia.put("Ambo", Arrays.asList("-Seleccione-", "Ambo", "Cayna", "Colpas", "Conchamarca", "Huacar", "San Francisco", "San Rafael", "Tomay Kichwa"));
            distritosPorProvincia.put("Dos de Mayo", Arrays.asList("-Seleccione-", "La Union", "Chuquis", "Marias", "Pachas", "Quivilla", "Ripan", "Shunqui", "Sillapata", "Yanas"));
            distritosPorProvincia.put("Huacaybamba", Arrays.asList("-Seleccione-", "Huacaybamba", "Canchabamba", "Cochabamba", "Pinra"));
            distritosPorProvincia.put("Huamalies", Arrays.asList("-Seleccione-", "Llata", "Arancay", "Chavin de Pariarca", "Jacas Grande", "Jircan", "Miraflores", "Monzon", "Punchao", "Punos", "Singa", "Tantamayo"));
            distritosPorProvincia.put("Huanuco", Arrays.asList("-Seleccione-", "Huanuco", "Amarilis", "Chinchao", "Churubamba", "Margos", "Quisqui", "San Francisco de Cayran", "San Pedro de Chaulan", "Santa Maria del Valle", "Yarumayo"));
            distritosPorProvincia.put("Leoncio Prado", Arrays.asList("-Seleccione-", "Rupa-Rupa", "Daniel Alomia Robles", "Hermilio Valdizan", "Jose Crespo y Castillo", "Luyando", "Mariano Damaso Beraun", "Pucayacu"));
            distritosPorProvincia.put("Maranon", Arrays.asList("-Seleccione-", "Huacrachuco", "Cholon", "San Buenaventura", "La Morada"));
            distritosPorProvincia.put("Pachitea", Arrays.asList("-Seleccione-", "Panao", "Chaglla", "Molino", "Umari"));
            distritosPorProvincia.put("Puerto Inca", Arrays.asList("-Seleccione-", "Puerto Inca", "Codo del Pozuzo", "Honoria", "Tournavista", "Yuyapichis"));
            distritosPorProvincia.put("Lauricocha", Arrays.asList("-Seleccione-", "Jesus", "Banos", "Jivia", "Queropalca", "Rondos", "San Francisco de Asis", "San Miguel de Cauri", "Choras"));
            distritosPorProvincia.put("Yarowilca", Arrays.asList("-Seleccione-", "Chavinillo", "Cahuac", "Chacabamba", "Aparicio Pomares", "Jacas Chico", "Obas", "Pampamarca", "Choras", "Yacus"));
            // Ica
            distritosPorProvincia.put("Chincha", Arrays.asList("-Seleccione-", "Chincha Alta", "Alto Laran", "Chavin", "Chincha Baja", "El Carmen", "Grocio Prado", "Pueblo Nuevo", "San Juan de Yanac", "San Pedro de Huacarpana", "Sunampe", "Tambo de Mora"));
            distritosPorProvincia.put("Ica", Arrays.asList("-Seleccione-", "Ica", "La Tingui�a", "Los Aquijes", "Ocucaje", "Pachacutec", "Parcona", "Pueblo Nuevo", "Salas", "San Jose de Los Molinos", "San Juan Bautista", "Santiago", "Subtanjalla", "Tate", "Yauca del Rosario"));
            distritosPorProvincia.put("Nazca", Arrays.asList("-Seleccione-", "Nazca", "Changuillo", "El Ingenio", "Marcona", "Vista Alegre"));
            distritosPorProvincia.put("Palpa", Arrays.asList("-Seleccione-", "Palpa", "Llipata", "Rio Grande", "Santa Cruz", "Tibillo"));
            distritosPorProvincia.put("Pisco", Arrays.asList("-Seleccione-", "Pisco", "Huancano", "Humay", "Independencia", "Paracas", "San Andres", "San Clemente", "Tupac Amaru Inca"));
            // Junin
            distritosPorProvincia.put("Chanchamayo", Arrays.asList("-Seleccione-", "Chanchamayo", "Perene", "Pichanaqui", "San Luis de Shuaro", "San Ramon", "Vitoc"));
            distritosPorProvincia.put("Chupaca", Arrays.asList("-Seleccione-", "Chupaca", "Ahuac", "Chongos Bajo", "Huachac", "Huamancaca Chico", "San Juan de Yscos", "San Juan de Jarpa", "Tres de Diciembre", "Yanacancha"));
            distritosPorProvincia.put("Concepcion", Arrays.asList("-Seleccione-", "Concepcion", "Aco", "Andamarca", "Chambara", "Cochas", "Comas", "Heroinas Toledo", "Manzanares", "Mariscal Castilla", "Matahuasi", "Mito", "Nueve de Julio", "Orcotuna", "San Jose de Quero", "Santa Rosa de Ocopa", "Vilca"));
            distritosPorProvincia.put("Huancayo", Arrays.asList("-Seleccione-", "Huancayo", "Carhuacallanga", "Chacapampa", "Chicche", "Chilca", "Chongos Alto", "Chupuro", "Colca", "Cullhuas", "El Tambo", "Huacrapuquio", "Hualhuas", "Huancan", "Huasicancha", "Huayucachi", "Ingenio", "Pariahuanca", "Pilcomayo", "Pucara", "Quichuay", "Quilcas", "San Agustin", "San Jeronimo de Tunan", "Sanos", "Sapallanga", "Sicaya", "Santo Domingo de Acobamba", "Viques"));
            distritosPorProvincia.put("Jauja", Arrays.asList("-Seleccione-", "Jauja", "Acolla", "Apata", "Ataura", "Canchayllo", "Curicaca", "El Mantaro", "Huamali", "Huaripampa", "Huertas", "Janjaillo", "Julcan", "Leonor Ordonez", "Llocllapampa", "Marco", "Masma", "Masma Chicche", "Molinos", "Monobamba", "Muqui", "Muquiyauyo", "Paca", "Paccha", "Pancan", "Parco", "Pomacancha", "Ricran", "San Lorenzo", "San Pedro de Chunan", "Sausa", "Sincos", "Tunan Marca", "Yauli", "Yauyos"));
            distritosPorProvincia.put("Junin", Arrays.asList("-Seleccione-", "Junin", "Carhuamayo", "Ondores", "Ulcumayo"));
            distritosPorProvincia.put("Satipo", Arrays.asList("-Seleccione-", "Satipo", "Coviriali", "Llaylla", "Mazamari", "Pampa Hermosa", "Pangoa", "Rio Negro", "Rio Tambo", "Vizcatan del Ene"));
            distritosPorProvincia.put("Tarma", Arrays.asList("-Seleccione-", "Tarma", "Acobamba", "Huaricolca", "Huasahuasi", "La Union", "Palca", "Palcamayo", "San Pedro de Cajas", "Tapo"));
            distritosPorProvincia.put("Yauli", Arrays.asList("-Seleccione-", "La Oroya", "Chacapalpa", "Huay-Huay", "Marcapomacocha", "Morococha", "Paccha", "Santa Barbara de Carhuacayan", "Santa Rosa de Sacco", "Suitucancha", "Yauli"));
            // La Libertad
            distritosPorProvincia.put("Ascope", Arrays.asList("-Seleccione-", "Ascope", "Casa Grande", "Chicama", "Chocope", "Magdalena de Cao", "Paijan", "Razuri", "Santiago de Cao"));
            distritosPorProvincia.put("Bolivar", Arrays.asList("-Seleccione-", "Bolivar", "Bambamarca", "Condormarca", "Longotea", "Uchumarca", "Ucuncha"));
            distritosPorProvincia.put("Chepen", Arrays.asList("-Seleccione-", "Chepen", "Pacanga", "Pueblo Nuevo"));
            distritosPorProvincia.put("Gran Chimu", Arrays.asList("-Seleccione-", "Cascas", "Lucma", "Marmot", "Sayapullo"));
            distritosPorProvincia.put("Julcan", Arrays.asList("-Seleccione-", "Julcan", "Calamarca", "Carabamba", "Huaso", "Huaylillas", "Mache", "Otuzco"));
            distritosPorProvincia.put("Otuzco", Arrays.asList("-Seleccione-", "Otuzco", "Agallpampa", "Charat", "Huaranchal", "La Cuesta", "Mache", "Paranday", "Salpo", "Sinsicap", "Usquil"));
            distritosPorProvincia.put("Pacasmayo", Arrays.asList("-Seleccione-", "Pacasmayo", "Guadalupe", "Jequetepeque", "Pacanga", "San Jose"));
            distritosPorProvincia.put("Pataz", Arrays.asList("-Seleccione-", "Tocache", "Huicungo", "Uchiza"));
            distritosPorProvincia.put("Sanchez Carrion", Arrays.asList("-Seleccione-", "Huamachuco", "Chugay", "Cochorco", "Curgos", "Marcabal", "Sanagoran", "Sarin", "Sartimbamba"));
            distritosPorProvincia.put("Santiago de Chuco", Arrays.asList("-Seleccione-", "Santiago de Chuco", "Angasmarca", "Cachicadan", "Mollebamba", "Mollepata", "Quiruvilca", "Santa Cruz de Chuca", "Sitabamba"));
            distritosPorProvincia.put("Trujillo", Arrays.asList("-Seleccione-", "Trujillo", "El Porvenir", "Florencia de Mora", "Huanchaco", "La Esperanza", "Laredo", "Moche", "Poroto", "Salaverry", "Simbal", "Victor Larco Herrera"));
            distritosPorProvincia.put("Viru", Arrays.asList("-Seleccione-", "Viru", "Chao", "Guadalupito"));
            // Lambayeque
            distritosPorProvincia.put("Chiclayo", Arrays.asList("-Seleccione-", "Chiclayo", "Chongoyape", "Eten", "Eten Puerto", "Jose Leonardo Ortiz", "La Victoria", "Lagunas", "Monsefu", "Nueva Arica", "Oyotun", "Picsi", "Pimentel", "Reque", "Santa Rosa", "Sa�a", "Tuman"));
            distritosPorProvincia.put("Ferrenafe", Arrays.asList("-Seleccione-", "Ferrenafe", "Canaris", "Incahuasi", "Manuel Antonio Mesones Muro", "Pitipo", "Pueblo Nuevo"));
            distritosPorProvincia.put("Lambayeque", Arrays.asList("-Seleccione-", "Lambayeque", "Chanaris", "Illimo", "Jayanca", "Mochumi", "Morrope", "Motupe", "Olmos", "Pacora", "Salas", "San Jose", "Tucume"));
            // Lima
            distritosPorProvincia.put("Barranca", Arrays.asList("-Seleccione-", "Barranca", "Paramonga", "Pativilca", "Supe", "Supe Puerto"));
            distritosPorProvincia.put("Cajatambo", Arrays.asList("-Seleccione-", "Cajatambo", "Copa", "Gorgor", "Huancapon", "Manas", "Cahuac"));
            distritosPorProvincia.put("Canta", Arrays.asList("-Seleccione-", "Canta", "Arahuay", "Huamantanga", "Huaros", "Lachaqui", "San Buenaventura", "Santa Rosa de Quives"));
            distritosPorProvincia.put("Ca�ete", Arrays.asList("-Seleccione-", "San Vicente", "Asia", "Calango", "Cerro Azul", "Chilca", "Coayllo", "Imperial", "Lunahuana", "Mala", "Nuevo Imperial", "Pacaran", "Quilmana", "San Antonio", "San Luis", "Santa Cruz de Flores", "Zu�iga"));
            distritosPorProvincia.put("Huaral", Arrays.asList("-Seleccione-", "Huaral", "Atavillos Alto", "Atavillos Bajo", "Aucallama", "Chancay", "Ihuari", "Lampian", "Pacaraos", "San Miguel de Acos", "Santa Cruz de Andamarca", "Sumbilca", "Veintisiete de Noviembre"));
            distritosPorProvincia.put("Huarochiri", Arrays.asList("-Seleccione-", "Matucana", "Antioquia", "Callahuanca", "Carampoma", "Chicla", "Cuenca", "Huachupampa", "Huanza", "Huarochiri", "Lahuaytambo", "Langa", "Laraos", "Mariatana", "Ricardo Palma", "San Andres de Tupicocha", "San Antonio", "San Bartolome", "San Damian", "San Juan de Iris", "San Juan de Tantaranche", "San Lorenzo de Quinti", "San Mateo", "San Mateo de Otao", "San Pedro de Casta", "San Pedro de Huancayre", "Sangallaya", "Santa Cruz de Cocachacra", "Santa Eulalia", "Santiago de Anchucaya", "Santiago de Tuna", "Santo Domingo de los Olleros", "Surco"));
            distritosPorProvincia.put("Huaura", Arrays.asList("-Seleccione-", "Huacho", "Ambar", "Caleta de Carquin", "Checras", "Hualmay", "Huaura", "Leoncio Prado", "Paccho", "Santa Leonor", "Santa Maria", "Sayan", "Vegueta"));
            distritosPorProvincia.put("Lima", Arrays.asList("-Seleccione-", "Ancon", "Ate", "Barranco", "Brena", "Carabayllo", "Chaclacayo", "Chorrillos", "Cieneguilla", "Comas", "El Agustino", "Independencia", "Jesus Maria", "La Molina", "La Victoria", "Lima", "Lince", "Los Olivos", "Lurigancho-Chosica", "Lurin", "Magdalena del Mar", "Miraflores", "Pachacamac", "Pucusana", "Pueblo Libre", "Puente Piedra", "Punta Hermosa", "Punta Negra", "Rimac", "San Bartolo", "San Borja", "San Isidro", "San Juan de Lurigancho", "San Juan de Miraflores", "San Luis", "San Martin de Porres", "San Miguel", "Santa Anita", "Santa Maria del Mar", "Santa Rosa", "Santiago de Surco", "Surquillo", "Villa El Salvador", "Villa Maria del Triunfo"));
            distritosPorProvincia.put("Oyon", Arrays.asList("-Seleccione-", "Oyon", "Andajes", "Caujul", "Cochamarca", "Navan", "Pachangara"));
            distritosPorProvincia.put("Yauyos", Arrays.asList("-Seleccione-", "Yauyos", "Alis", "Allauca", "Ayaviri", "Azangaro", "Cacra", "Carania", "Catahuasi", "Chocos", "Cochas", "Colonia", "Hongos", "Huampara", "Huancaya", "Huangascar", "Huantan", "Hua�ec", "Laraos", "Lincha", "Madean", "Miraflores", "Omas", "Putinza", "Quinches", "Quinocay", "San Joaquin", "San Pedro de Pilas", "Tanta", "Tauripampa", "Tomas", "Tupe", "Vi�ac", "Vitis", "Yauyos"));
            // Loreto
            distritosPorProvincia.put("Alto Amazonas", Arrays.asList("-Seleccione-", "Yurimaguas", "Balsapuerto", "Jeberos", "Lagunas", "Santa Cruz", "Teniente Cesar Lopez Rojas"));
            distritosPorProvincia.put("Loreto", Arrays.asList("-Seleccione-", "Nauta", "Parinari", "Tigre", "Trompeteros", "Urarinas"));
            distritosPorProvincia.put("Mariscal Ramon Castilla", Arrays.asList("-Seleccione-", "Caballococha", "Pebas", "San Pablo", "Yavari"));
            distritosPorProvincia.put("Maynas", Arrays.asList("-Seleccione-", "Iquitos", "Alto Nanay", "Fernando Lores", "Indiana", "Las Amazonas", "Mazan", "Napo", "Punchana", "Torres Causana", "Bel�n"));
            distritosPorProvincia.put("Requena", Arrays.asList("-Seleccione-", "Requena", "Alto Tapiche", "Capelo", "Emilio San Martin", "Maquia", "Puinahua", "Saquena", "Soplin", "Tapiche", "Jenaro Herrera", "Yaquerana"));
            distritosPorProvincia.put("Ucayali", Arrays.asList("-Seleccione-", "Contamana", "Inahuaya", "Padre Marquez", "Pampa Hermosa", "Sarayacu", "Vargas Guerra"));
            // Madre de Dios
            distritosPorProvincia.put("Manu", Arrays.asList("-Seleccione-", "Manu", "Fitzcarrald", "Madre de Dios", "Huepetuhe"));
            distritosPorProvincia.put("Tahuamanu", Arrays.asList("-Seleccione-", "I�apari", "Iberia", "Tahuamanu"));
            distritosPorProvincia.put("Tambopata", Arrays.asList("-Seleccione-", "Tambopata", "Inambari", "Las Piedras", "Laberinto"));
            // Moquegua
            distritosPorProvincia.put("General Sanchez Cerro", Arrays.asList("-Seleccione-", "Omate", "Chojata", "Coalaque", "Ichuna", "La Capilla", "Lloque", "Matalaque", "Puquina", "Quinistaquillas", "Ubinas", "Yunga"));
            distritosPorProvincia.put("Ilo", Arrays.asList("-Seleccione-", "Ilo", "Pacocha"));
            distritosPorProvincia.put("Mariscal Nieto", Arrays.asList("-Seleccione-", "Moquegua", "Carumas", "Cuchumbaya", "Samegua", "San Cristobal", "Torata", "Ichuna", "Lloque", "Matalaque", "Omate", "Puquina", "Ubinas", "Yunga"));
            // Pasco
            distritosPorProvincia.put("Daniel Alcides Carrion", Arrays.asList("-Seleccione-", "Yanahuanca", "Chacayan", "Goyllarisquizga", "Paucar", "San Pedro de Pillao", "Santa Ana de Tusi", "Tapuc", "Vilcabamba", "Yanahuanca"));
            distritosPorProvincia.put("Oxapampa", Arrays.asList("-Seleccione-", "Oxapampa", "Chontabamba", "Huancabamba", "Palcazu", "Pozuzo", "Puerto Bermudez", "Villa Rica"));
            distritosPorProvincia.put("Pasco", Arrays.asList("-Seleccione-", "Chaupimarca", "Huachon", "Huariaca", "Huayllay", "Ninacaca", "Pallanchacra", "Paucartambo", "San Francisco de Asis de Yarusyacan", "Simon Bolivar", "Ticlacayan", "Tinyahuarco", "Vicco", "Yanacancha", "Simon Bolivar"));
            // Piura
            distritosPorProvincia.put("Piura", Arrays.asList("-Seleccione-", "Piura", "Castilla", "Catacaos", "Cura Mori", "El Tallan", "La Arena", "La Union", "Las Lomas", "Tambo Grande"));
            distritosPorProvincia.put("Ayabaca", Arrays.asList("-Seleccione-", "Ayabaca", "Frias", "Jilili", "Lagunas", "Montero", "Pacaipampa", "Paimas", "Sapillica", "Sicchez", "Suyo"));
            distritosPorProvincia.put("Huancabamba", Arrays.asList("-Seleccione-", "Huancabamba", "Canchaque", "El Carmen de la Frontera", "Huarmaca", "Lalaquiz", "San Miguel de El Faique", "Sondor", "Sondorillo"));
            distritosPorProvincia.put("Morropon", Arrays.asList("-Seleccione-", "Chulucanas", "Buenos Aires", "Chalaco", "La Matanza", "Morropon", "Salitral", "San Juan de Bigote", "Santa Catalina de Mossa", "Santo Domingo", "Yamango"));
            distritosPorProvincia.put("Paita", Arrays.asList("-Seleccione-", "Paita", "Amotape", "Arenal", "Colan", "El Tallan", "La Arena", "La Huaca", "Tamarindo", "Vichayal"));
            distritosPorProvincia.put("Sechura", Arrays.asList("-Seleccione-", "Sechura", "Bellavista de la Union", "Bernal", "Cristo Nos Valga", "Vice", "Rinconada Llicuar", "El Alto de la Alianza", "Los Incas", "Cerro Colorado"));
            distritosPorProvincia.put("Sullana", Arrays.asList("-Seleccione-", "Sullana", "Bellavista", "Ignacio Escudero", "Lancones", "Marcavelica", "Miguel Checa", "Querecotillo", "Salitral", "El Alto de la Alianza", "Los Incas", "Cerro Colorado"));
            distritosPorProvincia.put("Talara", Arrays.asList("-Seleccione-", "Pari�as", "El Alto de la Alianza", "Los Incas", "Cerro Colorado"));
            // Puno
            distritosPorProvincia.put("Puno", Arrays.asList("-Seleccione-", "Puno", "Acora", "Amantani", "Atuncolla", "Capachica", "Chucuito", "Coata", "Huata", "Ma�azo", "Paucarcolla", "Pichacani", "Plateria", "San Antonio", "Tiquillaca", "Vilque"));
            distritosPorProvincia.put("Azangaro", Arrays.asList("-Seleccione-", "Azangaro", "Achaya", "Arapa", "Asillo", "Caminaca", "Chupa", "Jose Domingo Choquehuanca", "Mu�ani", "Potoni", "Saman", "San Anton", "San Jose", "San Juan de Salinas", "Santiago de Pupuja", "Tirapata"));
            distritosPorProvincia.put("Carabaya", Arrays.asList("-Seleccione-", "Macusani", "Ajoyani", "Ayapata", "Coasa", "Corani", "Crucero", "Ituata", "Ollachea", "San Gaban", "Usicayos"));
            distritosPorProvincia.put("Chucuito", Arrays.asList("-Seleccione-", "Juli", "Desaguadero", "Huacullani", "Kelluyo", "Pisacoma", "Pomata", "Zepita"));
            distritosPorProvincia.put("El Collao", Arrays.asList("-Seleccione-", "Ilave", "Capazo", "Pilcuyo", "Santa Rosa"));
            distritosPorProvincia.put("Huancane", Arrays.asList("-Seleccione-", "Huancane", "Cojata", "Huatasani", "Inchupalla", "Pusi", "Rosaspata", "Taraco", "Vilque Chico"));
            distritosPorProvincia.put("Lampa", Arrays.asList("-Seleccione-", "Lampa", "Cabanilla", "Calapuja", "Nicasio", "Ocuviri", "Palca", "Paratia", "Pucara", "Santa Lucia", "Vilavila"));
            distritosPorProvincia.put("Melgar", Arrays.asList("-Seleccione-", "Ayaviri", "Antauta", "Cupi", "Llalli", "Macari", "Nu�oa", "Orurillo", "Santa Rosa", "Umachiri"));
            distritosPorProvincia.put("Moho", Arrays.asList("-Seleccione-", "Moho", "Conima", "Huayrapata", "Tilali"));
            distritosPorProvincia.put("San Antonio de Putina", Arrays.asList("-Seleccione-", "Putina"));
            distritosPorProvincia.put("San Roman", Arrays.asList("-Seleccione-", "Juliaca", "Cabana", "Cabanillas", "Caracoto"));
            distritosPorProvincia.put("Sandia", Arrays.asList("-Seleccione-", "Sandia", "Cuyocuyo", "Limbani", "Patambuco", "Phara", "Quiaca", "San Juan del Oro", "Yanahuaya", "Alto Inambari", "San Pedro de Putina Punco", "Yunguyo"));
            distritosPorProvincia.put("Yunguyo", Arrays.asList("-Seleccione-", "Yunguyo", "Anapia", "Copani", "Cuturapi", "Ollaraya", "Tinicachi", "Unicachi"));
            // San Martin
            distritosPorProvincia.put("Moyobamba", Arrays.asList("-Seleccione-", "Moyobamba", "Calzada", "Habana", "Jepelacio", "Soritor", "Yantalo"));
            distritosPorProvincia.put("Bellavista", Arrays.asList("-Seleccione-", "Bellavista", "Alto Biavo", "Bajo Biavo", "Huallaga", "San Pablo", "San Rafael"));
            distritosPorProvincia.put("El Dorado", Arrays.asList("-Seleccione-", "San Jose de Sisa", "Agua Blanca", "San Martin", "Santa Rosa", "Shatoja"));
            distritosPorProvincia.put("Huallaga", Arrays.asList("-Seleccione-", "Saposoa", "Alto Saposoa", "El Eslabon", "Piscoyacu", "Sacanche", "Tingo de Saposoa", "Alto Saposoa"));
            distritosPorProvincia.put("Lamas", Arrays.asList("-Seleccione-", "Lamas", "Alonso de Alvarado", "Barranquita", "Caynarachi", "Cu�umbuqui", "Pinto Recodo", "Rumisapa", "San Roque de Cumbaza", "Shanao", "Tabalosos", "Zapatero"));
            distritosPorProvincia.put("Mariscal Caceres", Arrays.asList("-Seleccione-", "Juanjui", "Campanilla", "Huicungo", "Pachiza", "Pajarillo"));
            distritosPorProvincia.put("Picota", Arrays.asList("-Seleccione-", "Picota", "Buenos Aires", "Caspisapa", "Pilluana", "Pucacaca", "San Cristobal", "San Hilari�n", "Shamboyacu", "Tingo de Ponasa", "Tres Unidos"));
            distritosPorProvincia.put("Rioja", Arrays.asList("-Seleccione-", "Rioja", "Awajun", "Elias Soplin Vargas", "Nueva Cajamarca", "Pardo Miguel", "Posic", "San Fernando", "Yorongos", "Yuracyacu"));
            distritosPorProvincia.put("San Martin", Arrays.asList("-Seleccione-", "Tarapoto", "Alberto Leveau", "Cacatachi", "Chazuta", "Chipurana", "El Porvenir", "Huimbayoc", "Juan Guerra", "La Banda de Shilcayo", "Morales", "Papaplaya", "San Antonio", "Sauce", "Shapaja"));
            distritosPorProvincia.put("Tocache", Arrays.asList("-Seleccione-", "Tocache", "Nuevo Progreso", "Polvora", "Shunte", "Uchiza"));
            // Tacna
            distritosPorProvincia.put("Tacna", Arrays.asList("-Seleccione-", "Tacna", "Alto de la Alianza", "Calana", "Ciudad Nueva", "Inclan", "Pachia", "Palca", "Pocollay", "Sama"));
            distritosPorProvincia.put("Candarave", Arrays.asList("-Seleccione-", "Candarave", "Cairani", "Camilaca", "Curibaya", "Huanuara", "Quilahuani"));
            distritosPorProvincia.put("Jorge Basadre", Arrays.asList("-Seleccione-", "Locumba", "Ilabaya", "Ite"));
            distritosPorProvincia.put("Tarata", Arrays.asList("-Seleccione-", "Tarata", "Estique", "Estique-Pampa", "Heroes Albarracin", "Sitajara", "Susapaya", "Tarucachi", "Ticaco"));
            // Tumbes
            distritosPorProvincia.put("Tumbes", Arrays.asList("-Seleccione-", "Tumbes", "Corrales", "La Cruz", "Pampas de Hospital", "San Jacinto", "San Juan de la Virgen"));
            distritosPorProvincia.put("Contralmirante Villar", Arrays.asList("-Seleccione-", "Zorritos", "Casitas", "Canoas de Punta Sal"));
            distritosPorProvincia.put("Zarumilla", Arrays.asList("-Seleccione-", "Zarumilla", "Aguas Verdes", "Matapalo", "Papayal"));
            // Ucayali
            distritosPorProvincia.put("Coronel Portillo", Arrays.asList("-Seleccione-", "Calleria", "Campoverde", "Iparia", "Masisea", "Nueva Requena", "Yarinacocha"));
            distritosPorProvincia.put("Atalaya", Arrays.asList("-Seleccione-", "Raymondi", "Sepahua", "Tahuania", "Yurua"));
            distritosPorProvincia.put("Padre Abad", Arrays.asList("-Seleccione-", "Padre Abad", "Irazola", "Curimana"));
            distritosPorProvincia.put("Purus", Arrays.asList("-Seleccione-", "Purus"));
            
            List<String> distritos = distritosPorProvincia.get(provinciaSeleccionada);
            cboDistrito.removeAllItems();
            
            for(String distrito : distritos) {
                cboDistrito.addItem(distrito);
            }
        }
        
        /*DefaultComboBoxModel<String> distritoModel = (DefaultComboBoxModel<String>) cboDistrito.getModel();
        String provinciaSeleccionada = (String) cboProvincia.getSelectedItem();
        
        
        List<String> distritos = distritosPorProvincia.get(provinciaSeleccionada);
        distritoModel.removeAllElements();
        for (String distrito : distritos){
            distritoModel.addElement(distrito);
        }*/
    }//GEN-LAST:event_cboProvinciaItemStateChanged

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCrearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPacienteActionPerformed
        
    }//GEN-LAST:event_btnCrearPacienteActionPerformed

    PacienteController gestorPaciente = new PacienteController();

    private void limpiarCampos() {
        txtPNombre.setText("");
        txtSNombre.setText("");
        txtApellidoM.setText("");
        txtApellidoP.setText("");
        cboTipoDoc.setSelectedIndex(0);
        txtDocumento.setText("");
        cboTipoSexo.setSelectedIndex(0);
        cboTipoGrSa.setSelectedIndex(0);
        txtSeguroSocial.setText("");
        txtNacionalidad.setText("");
        dcFechaNacimiento.setDate(null);
        cboTipoEC.setSelectedIndex(0);
        txtTelefono.setText("");
        txtCorreoE.setText("");
        txtDireccion.setText("");
        cboDepartamento.setSelectedIndex(0);
        cboProvincia.setSelectedIndex(0);
        cboDistrito.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPaciente;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboDepartamento;
    private javax.swing.JComboBox<String> cboDistrito;
    private javax.swing.JComboBox<String> cboProvincia;
    private javax.swing.JComboBox<String> cboTipoDoc;
    private javax.swing.JComboBox<String> cboTipoEC;
    private javax.swing.JComboBox<String> cboTipoGrSa;
    private javax.swing.JComboBox<String> cboTipoSexo;
    private com.toedter.calendar.JDateChooser dcFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreoE;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtPNombre;
    private javax.swing.JTextField txtSNombre;
    private javax.swing.JTextField txtSeguroSocial;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
